### Get My Palette
GET  http://localhost:3002/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXRhbnNodXNhaHUiLCJpYXQiOjE3MTM5Njk5ODh9.nkR-dDndOKgCm3QHso9pa_NNhwj7GqfT7wUzNQsvqDg
